# Generated by Django 4.0.7 on 2022-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributor_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contactno', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('dateofbirth', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200, null=True)),
                ('organisation', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('education', models.CharField(max_length=200, null=True)),
                ('year_of_experience', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
