# Generated by Django 4.0.7 on 2022-08-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_distributor_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_form',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
