from django.db import models

# Create your models here.
class register(models.Model):
    username = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    contact = models.PositiveBigIntegerField()
    dateofbirth = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
class forms(models.Model):
    username = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    contact = models.PositiveBigIntegerField()
    view = models.BooleanField(default=False)


class reserch1(models.Model):
    Disease = models.CharField(max_length=200)
    symptoms = models.CharField(max_length=200)
    tablet = models.CharField(max_length=200)
    composition = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    Medicine = models.CharField(max_length=200)
    side_effect = models.CharField(max_length=200)
    sevearity = models.CharField(max_length=200)
    solution = models.CharField(max_length=200, null=True)
    accept = models.BooleanField(default=False)
    reject = models.BooleanField(default=False)
    send1 = models.BooleanField(default=False)
    packing_id1 = models.IntegerField(null=True)
    pack1 =models.BooleanField(default=False)
class reserch2(models.Model):
    Disease = models.CharField(max_length=200)
    symptoms = models.CharField(max_length=200)
    tablet = models.CharField(max_length=200)
    composition = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    Medicine = models.CharField(max_length=200)
    side_effect = models.CharField(max_length=200)
    sevearity = models.CharField(max_length=200)
    solution1 = models.CharField(max_length=200, null=True)
    accept1 = models.BooleanField(default=False)
    reject1 = models.BooleanField(default=False)
    send2 = models.BooleanField(default=False)
    packing_id2 = models.IntegerField(null=True)
    pack2 = models.BooleanField(default=False)
class reserch3(models.Model):
    Disease = models.CharField(max_length=200)
    symptoms = models.CharField(max_length=200)
    tablet = models.CharField(max_length=200)
    composition = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    Medicine = models.CharField(max_length=200)
    side_effect = models.CharField(max_length=200)
    sevearity = models.CharField(max_length=200)
    solution2 = models.CharField(max_length=200, null=True)
    accept2 = models.BooleanField(default=False)
    reject2 = models.BooleanField(default=False)
    send3 = models.BooleanField(default=False)
    packing_id3=models.IntegerField(null=True)
    pack3 = models.BooleanField(default=False)

class reserch4(models.Model):
    Disease = models.CharField(max_length=200)
    symptoms = models.CharField(max_length=200)
    tablet = models.CharField(max_length=200)
    composition = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    Medicine = models.CharField(max_length=200)
    side_effect = models.CharField(max_length=200)
    sevearity = models.CharField(max_length=200)
    solution3 = models.CharField(max_length=200, null=True)
    accept3 = models.BooleanField(default=False)
    reject3 = models.BooleanField(default=False)
    send4 = models.BooleanField(default=False)
    packing_id4 = models.IntegerField(null=True)
    pack4 = models.BooleanField(default=False)
class reserch5(models.Model):
    Disease = models.CharField(max_length=200)
    symptoms = models.CharField(max_length=200)
    tablet = models.CharField(max_length=200)
    composition = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    Medicine = models.CharField(max_length=200)
    side_effect = models.CharField(max_length=200)
    sevearity = models.CharField(max_length=200)
    solution4 = models.CharField(max_length=200, null=True)
    accept4 = models.BooleanField(default=False)
    reject4 = models.BooleanField(default=False)
    send5 = models.BooleanField(default=False)
    packing_id5 = models.IntegerField(null=True)
    pack5 = models.BooleanField(default=False)