# Generated by Django 4.0.7 on 2022-08-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='organisation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='year_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
