# Generated by Django 4.0.7 on 2022-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_form_degree_form_city_form_organisation_form_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
    ]
