# Generated by Django 4.0.7 on 2022-09-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_form_admin_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
