# Generated by Django 4.0.7 on 2022-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('tablet', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('Medicine', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('sevearity', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reserch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('tablet', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('Medicine', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('sevearity', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reserch3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('tablet', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('Medicine', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('sevearity', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reserch4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('tablet', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('Medicine', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('sevearity', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reserch5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('tablet', models.CharField(max_length=200)),
                ('composition', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('Medicine', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('side_effect', models.CharField(max_length=200)),
                ('sevearity', models.IntegerField(max_length=200)),
            ],
        ),
    ]
