# Generated by Django 4.0.7 on 2022-08-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_reserch1_reserch2_reserch3_reserch4_reserch5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserch1',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch1',
            name='sevearity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch2',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch2',
            name='sevearity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch3',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch3',
            name='sevearity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch4',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch4',
            name='sevearity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch5',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserch5',
            name='sevearity',
            field=models.IntegerField(),
        ),
    ]
