# Generated by Django 4.0.7 on 2022-08-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_reserch1_price_alter_reserch1_sevearity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserch1',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='reserch2',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='reserch3',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='reserch4',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='reserch5',
            name='usage',
        ),
    ]
