# Generated by Django 4.0.7 on 2022-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_reserch1_usage_remove_reserch2_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserch1',
            name='sevearity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reserch2',
            name='sevearity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reserch3',
            name='sevearity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reserch4',
            name='sevearity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reserch5',
            name='sevearity',
            field=models.CharField(max_length=200),
        ),
    ]
