# Generated by Django 4.0.7 on 2022-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_reserch1_sevearity_alter_reserch2_sevearity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserch1',
            name='solution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserch2',
            name='solution1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserch3',
            name='solution2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserch4',
            name='solution3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserch5',
            name='solution4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
