# Generated by Django 4.0.7 on 2022-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
