# Generated by Django 4.0.7 on 2022-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_forms_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserch1',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch1',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch2',
            name='accept1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch2',
            name='reject1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch3',
            name='accept2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch3',
            name='reject2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch4',
            name='accept3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch4',
            name='reject3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch5',
            name='accept4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch5',
            name='reject4',
            field=models.BooleanField(default=False),
        ),
    ]
