# Generated by Django 4.0.7 on 2022-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_reserch1_accept_reserch1_reject_reserch2_accept1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserch1',
            name='send1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch2',
            name='send2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch3',
            name='send3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch4',
            name='send4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch5',
            name='send5',
            field=models.BooleanField(default=False),
        ),
    ]
