# Generated by Django 4.0.7 on 2022-09-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_alter_reserch3_packing_id3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserch3',
            name='packing_id3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserch3',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
