# Generated by Django 4.0.7 on 2022-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_alter_reserch3_packing_id3_alter_reserch3_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserch1',
            name='packing_id1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserch2',
            name='packing_id2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserch4',
            name='packing_id4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserch5',
            name='packing_id5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserch1',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserch2',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserch4',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reserch5',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
