# Generated by Django 4.0.7 on 2022-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_reserch1_packing_id1_reserch2_packing_id2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserch1',
            name='pack1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch2',
            name='pack2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch3',
            name='pack3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch4',
            name='pack4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserch5',
            name='pack5',
            field=models.BooleanField(default=False),
        ),
    ]
